ALTER TABLE public.tracking_logs 
ADD COLUMN IF NOT EXISTS vessel_name TEXT,
ADD COLUMN IF NOT EXISTS mmsi TEXT,
ADD COLUMN IF NOT EXISTS imo TEXT,
ADD COLUMN IF NOT EXISTS flag TEXT,
ADD COLUMN IF NOT EXISTS call_sign TEXT,
ADD COLUMN IF NOT EXISTS vessel_type TEXT,
ADD COLUMN IF NOT EXISTS length NUMERIC,
ADD COLUMN IF NOT EXISTS beam NUMERIC,
ADD COLUMN IF NOT EXISTS draught NUMERIC,
ADD COLUMN IF NOT EXISTS area TEXT,
ADD COLUMN IF NOT EXISTS speed_knots NUMERIC,
ADD COLUMN IF NOT EXISTS course NUMERIC,
ADD COLUMN IF NOT EXISTS status TEXT,
ADD COLUMN IF NOT EXISTS previous_port JSONB,
ADD COLUMN IF NOT EXISTS current_port JSONB,
ADD COLUMN IF NOT EXISTS next_port JSONB,
ADD COLUMN IF NOT EXISTS api_updated_at TIMESTAMPTZ;

-- Drop old columns if they exist and are no longer needed (optional)
-- ALTER TABLE public.tracking_logs DROP COLUMN IF EXISTS status_text;
